# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssd < Formula
  desc "Agentless remote deployment tool for Docker Compose stacks"
  homepage "https://github.com/byteink/ssd"
  version "0.27.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteink/ssd/releases/download/v0.27.1/ssd_Darwin_x86_64.tar.gz"
      sha256 "93f7f5fcf570fa8b4b81ed134577495db5bdf2c71205df96d80b91e3ff51229a"

      define_method(:install) do
        bin.install "ssd"
        (share/"ssd").install "skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteink/ssd/releases/download/v0.27.1/ssd_Darwin_arm64.tar.gz"
      sha256 "6dd3c89a846544b19ecfba3410bb9185c0a58d6955b2adf348e4e70302fe16f1"

      define_method(:install) do
        bin.install "ssd"
        (share/"ssd").install "skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteink/ssd/releases/download/v0.27.1/ssd_Linux_x86_64.tar.gz"
      sha256 "2558746ab2519172bc3e2abab6378bf80e5f2d5518282d48c3b46f2301342071"
      define_method(:install) do
        bin.install "ssd"
        (share/"ssd").install "skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteink/ssd/releases/download/v0.27.1/ssd_Linux_arm64.tar.gz"
      sha256 "59d9f9f914ded3a962c949f7e8cbb1d1130a869300cc3b303a33c7f26c68660a"
      define_method(:install) do
        bin.install "ssd"
        (share/"ssd").install "skill"
      end
    end
  end

  test do
    system "#{bin}/ssd", "version"
  end
end
