# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssd < Formula
  desc "Agentless remote deployment tool for Docker Compose stacks"
  homepage "https://github.com/byteink/ssd"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/byteink/ssd/releases/download/v0.1.2/ssd_Darwin_x86_64.tar.gz"
      sha256 "371bfdbcd20c5a0e36691bd29833ccd787e539723c0ce5729dc0c92f22380f9a"

      def install
        bin.install "ssd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/byteink/ssd/releases/download/v0.1.2/ssd_Darwin_arm64.tar.gz"
      sha256 "ba4420a239ff6f684ecc14fbf64d451cdee8334be1914a7188b81a616e013ae6"

      def install
        bin.install "ssd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteink/ssd/releases/download/v0.1.2/ssd_Linux_x86_64.tar.gz"
      sha256 "9146fe9beda22ded496b2bdda18a760a7c6ae93b8d6a7c64be1c919181700133"
      def install
        bin.install "ssd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/byteink/ssd/releases/download/v0.1.2/ssd_Linux_arm64.tar.gz"
      sha256 "fb14a22fc2828d408b04391ed3acb259fbfd1c83d787fc33562bff4ee1e42a50"
      def install
        bin.install "ssd"
      end
    end
  end

  test do
    system "#{bin}/ssd", "version"
  end
end
